/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JavaHowTo */

#ifndef _Included_JavaHowTo
#define _Included_JavaHowTo
#ifdef __cplusplus
extern "C" {
#endif
#undef JavaHowTo_FOREGROUND_BLACK
#define JavaHowTo_FOREGROUND_BLACK 0L
#undef JavaHowTo_FOREGROUND_BLUE
#define JavaHowTo_FOREGROUND_BLUE 1L
#undef JavaHowTo_FOREGROUND_GREEN
#define JavaHowTo_FOREGROUND_GREEN 2L
#undef JavaHowTo_FOREGROUND_RED
#define JavaHowTo_FOREGROUND_RED 4L
#undef JavaHowTo_FOREGROUND_WHITE
#define JavaHowTo_FOREGROUND_WHITE 7L
#undef JavaHowTo_FOREGROUND_INTENSITY
#define JavaHowTo_FOREGROUND_INTENSITY 8L
#undef JavaHowTo_BACKGROUND_BLUE
#define JavaHowTo_BACKGROUND_BLUE 16L
#undef JavaHowTo_BACKGROUND_GREEN
#define JavaHowTo_BACKGROUND_GREEN 32L
#undef JavaHowTo_BACKGROUND_RED
#define JavaHowTo_BACKGROUND_RED 64L
#undef JavaHowTo_BACKGROUND_INTENSITY
#define JavaHowTo_BACKGROUND_INTENSITY 128L
/*
 * Class:     JavaHowTo
 * Method:    cls
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JavaHowTo_cls
  (JNIEnv *, jobject);

/*
 * Class:     JavaHowTo
 * Method:    setCursorPosition
 * Signature: (SS)V
 */
JNIEXPORT void JNICALL Java_JavaHowTo_setCursorPosition
  (JNIEnv *, jobject, jshort, jshort);

/*
 * Class:     JavaHowTo
 * Method:    keepColors
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JavaHowTo_keepColors
  (JNIEnv *, jobject);

/*
 * Class:     JavaHowTo
 * Method:    restoreColors
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JavaHowTo_restoreColors
  (JNIEnv *, jobject);

/*
 * Class:     JavaHowTo
 * Method:    setColor
 * Signature: (SS)V
 */
JNIEXPORT void JNICALL Java_JavaHowTo_setColor
  (JNIEnv *, jobject, jshort, jshort);

#ifdef __cplusplus
}
#endif
#endif
